//
// Speech.cs - Copyright (c) 2006-2022 Josh Dersch (derschjo@gmail.com)
//
// This file is part of PERQemu.
//
// PERQemu is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PERQemu is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PERQemu.  If not, see <http://www.gnu.org/licenses/>.
//

using System;

using PERQemu.IO.Z80;
using PERQemu.IO.SerialDevices;
using System.IO.Ports;

namespace PERQemu.IO.SerialDevices
{
    /// <summary>
    /// The PERQ "speech" device uses the MC3417 CVSD chip to produce audio
    /// output from a serial byte stream (an SIO channel) with a baud clock
    /// generated by the CTC.  This is a placeholder for future connections
    /// to the SDL2 audio plumbing for host output.
    /// </summary>
    public class Speech : ISerialDevice, ISIODevice
    {
        public Speech()
        {
        }


        public string Port
        {
            get { throw new NotImplementedException(); }
            set { throw new NotImplementedException(); }
        }

        public bool IsOpen
        {
            get { throw new NotImplementedException(); }
        }

        public int BaudRate
        {
            get { throw new NotImplementedException(); }
        }

        public int ByteCount
        {
            get { throw new NotImplementedException(); }
        }

        public int DataBits
        {
            get { throw new NotImplementedException(); }
            set { throw new NotImplementedException(); }
        }

        public Parity Parity
        {
            get { throw new NotImplementedException(); }
            set { throw new NotImplementedException(); }
        }

        public StopBits StopBits
        {
            get { throw new NotImplementedException(); }
            set { throw new NotImplementedException(); }
        }

        public bool DTR
        {
            get { throw new NotImplementedException(); }
            set { throw new NotImplementedException(); }
        }

        public bool RTS
        {
            get { throw new NotImplementedException(); }
            set { throw new NotImplementedException(); }
        }

        public bool DCD
        {
            get { throw new NotImplementedException(); }
        }

        public bool CTS
        {
            get { throw new NotImplementedException(); }
        }

        public bool DSR
        {
            get { throw new NotImplementedException(); }
        }

        public void Reset()
        {
            throw new NotImplementedException();
        }

        public void Open()
        {
            throw new NotImplementedException();
        }

        public void Close()
        {
            throw new NotImplementedException();
        }

        public void NotifyRateChange(int newRate)
        {
            throw new NotImplementedException();
        }

        public byte ReadByte()
        {
            throw new NotImplementedException();
        }

        public void Write(byte[] data, int index, int length)
        {
            throw new NotImplementedException();
        }

        public void WriteByte(byte b)
        {
            throw new NotImplementedException();
        }

        //
        // ISIODevice implementation
        //

        public void RegisterReceiveDelegate(ReceiveDelegate rxDelegate)
        {
            throw new NotImplementedException();
        }

        public void Transmit(byte value)
        {
            throw new NotImplementedException();
        }

        public void TransmitAbort()
        {
            throw new NotImplementedException();
        }

        public void TransmitBreak()
        {
            throw new NotImplementedException();
        }

        public void Status()
        {
            throw new NotImplementedException();
        }

        public void RegisterStatusDelegate(ReceiveStatusDelegate rxDelegate)
        {
            throw new NotImplementedException();
        }
    }
}
