// qcode.cs - Copyright 2006-2016 Josh Dersch (derschjo@gmail.com)
//
// This file is part of PERQemu.
//
// PERQemu is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PERQemu is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PERQemu.  If not, see <http://www.gnu.org/licenses/>.
//

using System;

namespace PERQemu.QCode
{
    /// <summary>
    /// Represents a single QCode instruction; includes a mapping from
    /// the Code to its Mnemonic; may be extended to include other info at
    /// some point...
    /// </summary>
    public class QCode
    {
        public QCode(byte code, string mnemonic)
        {
            Code = code;
            Mnemonic = mnemonic;
        }

        public byte Code;
        public string Mnemonic;
    }

    /// <summary>
    /// Contains methods and structures to aid in disassembling POS and Accent PERQ Q-Code.
    /// Somewhat useful when debugging emulation issues in the POS Q-Code interpreter...
    /// TODO: Create other classes for dealing with other bytecodes (PNX C-Code, for example...)
    /// TODO: Make it possible to switch between mappings in the debugger.
    /// </summary>
    public static class QCodeHelper
    {
        static QCodeHelper()
        {
            BuildTables(_qCodesAccentUnordered);
        }

        public static QCode GetQCodeFromOpCode(byte opCode)
        {
            QCode q = _qCodesOrdered[opCode];

            if (q == null)
            {
                q = new QCode(opCode, "!! INVALID QCODE !!");
            }

            return q;
        }

        private static void BuildTables(QCode[] unordered)
        {
            _qCodesOrdered = new QCode[256];

            for (int i = 0; i < unordered.Length; i++)
            {
                int index = unordered[i].Code;

                if (_qCodesOrdered[index] != null)
                {
                    throw new InvalidOperationException(String.Format("Duplicate QCode entry {0}", index));
                }

                _qCodesOrdered[index] = unordered[i];
            }
        }

        /// <summary>
        /// Ordered table of QCodes, computed at runtime.
        /// </summary>
        private static QCode[] _qCodesOrdered;

        /// <summary>
        /// Unordered Table of QCodes for POS.
        /// These don't _need_ to be in order, but they happen to be except for
        /// invalid opcodes which are skipped.
        /// _qCodesOrdered will be populated at runtime with a sorted list for easy indexing.
        /// </summary>
        private static QCode[] _qCodesPOSUnordered =
        {
            new QCode( 0, "LDC0"),
            new QCode( 1, "LDC1"),
            new QCode( 2, "LDC2"),
            new QCode( 3, "LDC3"),
            new QCode( 4, "LDC4"),
            new QCode( 5, "LDC5"),
            new QCode( 6, "LDC6"),
            new QCode( 7, "LDC7"),
            new QCode( 8, "LDC8"),
            new QCode( 9, "LDC9"),
            new QCode( 10, "LDC10"),
            new QCode( 11, "LDC11"),
            new QCode( 12, "LDC12"),
            new QCode( 13, "LDC13"),
            new QCode( 14, "LDC14"),
            new QCode( 15, "LDC15"),
            new QCode( 16, "LDCMO"),
            new QCode( 17, "LDCB"),
            new QCode( 18, "LDCW"),
            new QCode( 19, "LSA"),
            new QCode( 20, "ROTSHI"),
            new QCode( 21, "STIND"),
            new QCode( 22, "LDCN"),
            new QCode( 23, "LDB"),
            new QCode( 24, "STB"),
            new QCode( 25, "LDCH"),
            new QCode( 26, "LDP"),
            new QCode( 27, "STP"),
            new QCode( 28, "STCH"),
            new QCode( 29, "EXGO"),
            new QCode( 30, "LAND"),
            new QCode( 31, "LOR"),
            new QCode( 32, "LNOT"),
            new QCode( 33, "EQUBool"),
            new QCode( 34, "NEQBool"),
            new QCode( 35, "LEQBool"),
            new QCode( 36, "LESBool"),
            new QCode( 37, "GEQBool"),
            new QCode( 38, "GTRBool"),
            new QCode( 39, "EQUI"),
            new QCode( 40, "NEQI"),
            new QCode( 41, "LEQI"),
            new QCode( 42, "LESI"),
            new QCode( 43, "GEQI"),
            new QCode( 44, "GTRI"),
            new QCode( 51, "EQUStr"),
            new QCode( 52, "NEQStr"),
            new QCode( 53, "LEQStr"),
            new QCode( 54, "LESStr"),
            new QCode( 55, "GEQStr"),
            new QCode( 56, "GTRStr"),
            new QCode( 57, "EQUByt"),
            new QCode( 58, "NEQByt"),
            new QCode( 59, "LEQByt"),
            new QCode( 60, "LESByt"),
            new QCode( 61, "GEQByt"),
            new QCode( 62, "GTRByt"),
            new QCode( 63, "EQUPowr"),
            new QCode( 64, "NEQPowr"),
            new QCode( 65, "LEQPower"),
            new QCode( 66, "SGS"),
            new QCode( 67, "GEQPower"),
            new QCode( 68, "SRS"),
            new QCode( 69, "EQUWord"),
            new QCode( 70, "NEQWord"),
            new QCode( 71, "ABI"),
            new QCode( 72, "ADI"),
            new QCode( 73, "NGI"),
            new QCode( 74, "SBI"),
            new QCode( 75, "MPI"),
            new QCode( 76, "DVI"),
            new QCode( 77, "MODI"),
            new QCode( 78, "CHK"),
            new QCode( 88, "INN"),
            new QCode( 89, "UNI"),
            new QCode( 90, "QINT"),
            new QCode( 91, "DIF"),
            new QCode( 92, "EXIT"),
            new QCode( 93, "NOOP"),
            new QCode( 94, "REPL"),
            new QCode( 95, "REPL2"),
            new QCode( 96, "MMS"),
            new QCode( 97, "MES"),
            new QCode( 98, "LVRD"),
            new QCode( 99, "LSSN"),
            new QCode( 100, "XJP"),
            new QCode( 102, "RASTEROP"),
            new QCode( 103, "STARTIO"),
            new QCode( 105, "INTOFF"),
            new QCode( 106, "INTON"),
            new QCode( 107, "LDLB"),
            new QCode( 108, "LDLW"),
            new QCode( 109, "LDL0"),
            new QCode( 110, "LDL1"),
            new QCode( 111, "LDL2"),
            new QCode( 112, "LDL3"),
            new QCode( 113, "LDL4"),
            new QCode( 114, "LDL5"),
            new QCode( 115, "LDL6"),
            new QCode( 116, "LDL7"),
            new QCode( 117, "LDL8"),
            new QCode( 118, "LDL9"),
            new QCode( 119, "LDL10"),
            new QCode( 120, "LDL11"),
            new QCode( 121, "LDL12"),
            new QCode( 122, "LDL13"),
            new QCode( 123, "LDL14"),
            new QCode( 124, "LDL15"),
            new QCode( 125, "LLAB"),
            new QCode( 126, "LLAW"),
            new QCode( 127, "STLB"),
            new QCode( 128, "STLW"),
            new QCode( 129, "STL0"),
            new QCode( 130, "STL1"),
            new QCode( 131, "STL2"),
            new QCode( 132, "STL3"),
            new QCode( 133, "STL4"),
            new QCode( 134, "STL5"),
            new QCode( 135, "STL6"),
            new QCode( 136, "STL7"),
            new QCode( 137, "LDOB"),
            new QCode( 138, "LDOW"),
            new QCode( 139, "LDO0"),
            new QCode( 140, "LDO1"),
            new QCode( 141, "LDO2"),
            new QCode( 142, "LDO3"),
            new QCode( 143, "LDO4"),
            new QCode( 144, "LDO5"),
            new QCode( 145, "LDO6"),
            new QCode( 146, "LDO7"),
            new QCode( 147, "LDO8"),
            new QCode( 148, "LDO9"),
            new QCode( 149, "LDO10"),
            new QCode( 150, "LDO11"),
            new QCode( 151, "LDO12"),
            new QCode( 152, "LDO13"),
            new QCode( 153, "LDO14"),
            new QCode( 154, "LDO15"),
            new QCode( 155, "LOAB"),
            new QCode( 156, "LOAW"),
            new QCode( 157, "STOB"),
            new QCode( 158, "STOW"),
            new QCode( 159, "STO0"),
            new QCode( 160, "STO1"),
            new QCode( 161, "STO2"),
            new QCode( 162, "STO3"),
            new QCode( 163, "STO4"),
            new QCode( 164, "STO5"),
            new QCode( 165, "STO6"),
            new QCode( 166, "STO7"),
            new QCode( 167, "MVBB"),
            new QCode( 168, "MVBW"),
            new QCode( 169, "MOVB"),
            new QCode( 170, "MOVW"),
            new QCode( 171, "INDB"),
            new QCode( 172, "INDW"),
            new QCode( 173, "SIND0"),
            new QCode( 174, "SIND1"),
            new QCode( 175, "SIND2"),
            new QCode( 176, "SIND3"),
            new QCode( 177, "SIND4"),
            new QCode( 178, "SIND5"),
            new QCode( 179, "SIND6"),
            new QCode( 180, "INSD7"),
            new QCode( 181, "LGAWW"),
            new QCode( 182, "STMW"),
            new QCode( 183, "STDW"),
            new QCode( 184, "SAS"),
            new QCode( 185, "ADJ"),
            new QCode( 186, "CALL"),
            new QCode( 187, "CALLV"),
            new QCode( 188, "ATPB"),
            new QCode( 189, "ATPW"),
            new QCode( 190, "WCS"),
            new QCode( 191, "JCS"),
            new QCode( 192, "LDGB"),
            new QCode( 193, "LDGW"),
            new QCode( 194, "LGAB"),
            new QCode( 195, "LGAW"),
            new QCode( 196, "STGB"),
            new QCode( 197, "STGW"),
            new QCode( 200, "RETURN"),
            new QCode( 201, "MMS2"),
            new QCode( 202, "MES2"),
            new QCode( 203, "LDTP"),
            new QCode( 204, "JMPB"),
            new QCode( 205, "JMPW"),
            new QCode( 206, "JFB"),
            new QCode( 207, "JFW"),
            new QCode( 208, "JTB"),
            new QCode( 209, "JTW"),
            new QCode( 210, "JEQB"),
            new QCode( 211, "JEQW"),
            new QCode( 212, "JNEB"),
            new QCode( 213, "JNEW"),
            new QCode( 214, "IXP"),
            new QCode( 215, "LDIB"),
            new QCode( 216, "LDIW"),
            new QCode( 217, "LIAB"),
            new QCode( 218, "LIAW"),
            new QCode( 219, "STIB"),
            new QCode( 220, "STIW"),
            new QCode( 221, "IXAB"),
            new QCode( 222, "IXAW"),
            new QCode( 223, "IXA1"),
            new QCode( 224, "IXA2"),
            new QCode( 225, "IXA3"),
            new QCode( 226, "IXA4"),
            new QCode( 227, "TLATE0"),
            new QCode( 228, "TLATE1"),
            new QCode( 229, "TLATE2"),
            new QCode( 230, "EXCH"),
            new QCode( 231, "EXCH2"),
            new QCode( 232, "INCB"),
            new QCode( 233, "INCW"),
            new QCode( 234, "CALLXB"),
            new QCode( 235, "CALLXW"),
            new QCode( 236, "LDMC"),
            new QCode( 237, "LDDC"),
            new QCode( 238, "LDMW"),
            new QCode( 239, "LDDW"),
            new QCode( 240, "STLATE"),
            new QCode( 241, "LINE"),
            new QCode( 242, "ENABLE"),
            new QCode( 243, "RAISE"),
            new QCode( 244, "LDAP"),
            new QCode( 250, "ROPS"),
            new QCode( 251, "INCDDS"),
            new QCode( 252, "LOPS"),
            new QCode( 254, "BREAK"),
            new QCode( 255, "REFILLOP")
        };


        /// <summary>
        /// Unordered Table of QCodes for Accent S4.  (And possibly later versions)
        /// These don't _need_ to be in order, but they happen to be except for
        /// invalid opcodes which are skipped.
        /// _qCodesOrdered will be populated at runtime with a sorted list for easy indexing.
        /// </summary>
        private static QCode[] _qCodesAccentUnordered =
        {
            new QCode( 0, "LDC0"),
            new QCode( 1, "LDC1"),
            new QCode( 2, "LDC2"),
            new QCode( 3, "LDC3"),
            new QCode( 4, "LDC4"),
            new QCode( 5, "LDC5"),
            new QCode( 6, "LDC6"),
            new QCode( 7, "LDC7"),
            new QCode( 8, "LDC8"),
            new QCode( 9, "LDC9"),
            new QCode( 10, "LDC10"),
            new QCode( 11, "LDC11"),
            new QCode( 12, "LDC12"),
            new QCode( 13, "LDC13"),
            new QCode( 14, "LDC14"),
            new QCode( 15, "LDC15"),
            new QCode( 16, "LDCMO"),
            new QCode( 17, "LDCB"),
            new QCode( 18, "LDCW"),
            new QCode( 19, "LSA"),
            new QCode( 20, "ROTSHI"),
            new QCode( 21, "STIND"),
            new QCode( 22, "LDCN"),
            new QCode( 23, "LDB"),
            new QCode( 24, "STB"),
            new QCode( 25, "LDCH"),
            new QCode( 26, "LDP"),
            new QCode( 27, "STP"),
            new QCode( 28, "STCH"),
            new QCode( 29, "EXGO"),
            new QCode( 30, "LAND"),
            new QCode( 31, "LOR"),
            new QCode( 32, "LNOT"),
            new QCode( 33, "EQUBool"),
            new QCode( 34, "NEQBool"),
            new QCode( 35, "LEQBool"),
            new QCode( 36, "LESBool"),
            new QCode( 37, "GEQBool"),
            new QCode( 38, "GTRBool"),
            new QCode( 39, "EQUI"),
            new QCode( 40, "NEQI"),
            new QCode( 41, "LEQI"),
            new QCode( 42, "LESI"),
            new QCode( 43, "GEQI"),
            new QCode( 44, "GTRI"),
            new QCode( 45, "EQUptr"),
            new QCode( 46, "NEQPtr"),
            new QCode( 47, "LLLB"),
            new QCode( 48, "LLLW"),
            new QCode( 49, "LILB"),
            new QCode( 50, "LILW"),
            new QCode( 51, "EQUStr"),
            new QCode( 52, "NEQStr"),
            new QCode( 53, "LEQStr"),
            new QCode( 54, "LESStr"),
            new QCode( 55, "GEQStr"),
            new QCode( 56, "GTRStr"),
            new QCode( 57, "EQUByt"),
            new QCode( 58, "NEQByt"),
            new QCode( 59, "LEQByt"),
            new QCode( 60, "LESByt"),
            new QCode( 61, "GEQByt"),
            new QCode( 62, "GTRByt"),
            new QCode( 63, "EQUPowr"),
            new QCode( 64, "NEQPowr"),
            new QCode( 65, "LEQPower"),
            new QCode( 66, "SGS"),
            new QCode( 67, "GEQPower"),
            new QCode( 68, "SRS"),
            new QCode( 69, "EQUWord"),
            new QCode( 70, "NEQWord"),
            new QCode( 71, "ABI"),
            new QCode( 72, "ADI"),
            new QCode( 73, "NGI"),
            new QCode( 74, "SBI"),
            new QCode( 75, "MPI"),
            new QCode( 76, "DVI"),
            new QCode( 77, "MODI"),
            new QCode( 78, "CHK"),
            new QCode( 79, "LOLB"),
            new QCode( 80, "LOLW"),
            new QCode( 81, "SLLB"),
            new QCode( 82, "SLLW"),
            new QCode( 83, "SILB"),
            new QCode( 84, "SILW"),
            new QCode( 85, "SOLB"),
            new QCode( 86, "SOLW"),
            new QCode( 87, "GOTOOVL"),
            new QCode( 88, "INN"),
            new QCode( 89, "UNI"),
            new QCode( 90, "QINT"),
            new QCode( 91, "DIF"),
            new QCode( 92, "EXITT"),
            new QCode( 93, "NOOP"),
            new QCode( 94, "REPL"),
            new QCode( 95, "REPL2"),
            new QCode( 96, "MMS"),
            new QCode( 97, "MES"),
            new QCode( 98, "LVRD"),
            new QCode( 99, "LDRET1"),
            new QCode( 100, "XJP"),
            new QCode( 101, "LDRET2"),
            new QCode( 102, "RASTEROP"),
            new QCode( 103, "STARTIO"),
            new QCode( 104, "STRROP"),
            new QCode( 105, "LDBIND"),
            new QCode( 106, "STBIND"),
            new QCode( 107, "LDLB"),
            new QCode( 108, "LDLW"),
            new QCode( 109, "LDL0"),
            new QCode( 110, "LDL1"),
            new QCode( 111, "LDL2"),
            new QCode( 112, "LDL3"),
            new QCode( 113, "LDL4"),
            new QCode( 114, "LDL5"),
            new QCode( 115, "LDL6"),
            new QCode( 116, "LDL7"),
            new QCode( 117, "LDL8"),
            new QCode( 118, "LDL9"),
            new QCode( 119, "LDL10"),
            new QCode( 120, "LDL11"),
            new QCode( 121, "LDL12"),
            new QCode( 122, "LDL13"),
            new QCode( 123, "LDL14"),
            new QCode( 124, "LDL15"),
            new QCode( 125, "LLAB"),
            new QCode( 126, "LLAW"),
            new QCode( 127, "STLB"),
            new QCode( 128, "STLW"),
            new QCode( 129, "STL0"),
            new QCode( 130, "STL1"),
            new QCode( 131, "STL2"),
            new QCode( 132, "STL3"),
            new QCode( 133, "STL4"),
            new QCode( 134, "STL5"),
            new QCode( 135, "STL6"),
            new QCode( 136, "STL7"),
            new QCode( 137, "LDOB"),
            new QCode( 138, "LDOW"),
            new QCode( 139, "LDREG0"),
            new QCode( 140, "LDREG1"),
            new QCode( 141, "LDREG2"),
            new QCode( 142, "LDREG3"),
            new QCode( 143, "STREG0"),
            new QCode( 144, "STREG1"),
            new QCode( 145, "STREG2"),
            new QCode( 146, "STREG3"),
            new QCode( 147, "LDLCB"),
            new QCode( 148, "LDLIND"),
            new QCode( 149, "UNDF149"),
            new QCode( 150, "EXOP"),
            new QCode( 151, "LDLC1"),
            new QCode( 152, "LDLCM1"),
            new QCode( 153, "nCVTLI"),
            new QCode( 154, "nCVTIL"),
            new QCode( 155, "LOAB"),
            new QCode( 156, "LOAW"),
            new QCode( 157, "STOB"),
            new QCode( 158, "STOW"),
            new QCode( 159, "nADL"),
            new QCode( 160, "nSBL"),
            new QCode( 161, "nEQLONG"),
            new QCode( 162, "nNEQLONG"),
            new QCode( 163, "nLEQLONG"),
            new QCode( 164, "nLESLONG"),
            new QCode( 165, "nGEQLONG"),
            new QCode( 166, "nGTRLONG"),
            new QCode( 167, "MVBB"),
            new QCode( 168, "MVBW"),
            new QCode( 169, "MOVB"),
            new QCode( 170, "MOVW"),
            new QCode( 171, "INDB"),
            new QCode( 172, "INDW"),
            new QCode( 173, "LDIND/IND0"),
            new QCode( 174, "IND1"),
            new QCode( 175, "IND2"),
            new QCode( 176, "IND3"),
            new QCode( 177, "IND4"),
            new QCode( 178, "IND5"),
            new QCode( 179, "IND6"),
            new QCode( 180, "NSD7"),
            new QCode( 181, "LGAWW"),
            new QCode( 182, "STMW"),
            new QCode( 183, "STDW"),
            new QCode( 184, "SAS"),
            new QCode( 185, "ADJ"),
            new QCode( 186, "CALLL"),
            new QCode( 187, "CALLV"),
            new QCode( 188, "ATPB"),
            new QCode( 189, "ATPW"),
            new QCode( 190, "WCS"),
            new QCode( 191, "JCS"),
            new QCode( 192, "LDGB"),
            new QCode( 193, "LDGW"),
            new QCode( 194, "LGAB"),
            new QCode( 195, "LGAW"),
            new QCode( 196, "STGB"),
            new QCode( 197, "STGW"),
            new QCode( 198, "SGLB"),
            new QCode( 199, "SGLW"),
            new QCode( 200, "RET"),
            new QCode( 201, "MMS2"),
            new QCode( 202, "MES2"),
            new QCode( 203, "LDTP"),
            new QCode( 204, "JMPB"),
            new QCode( 205, "JMPW"),
            new QCode( 206, "JFB"),
            new QCode( 207, "JFW"),
            new QCode( 208, "JTB"),
            new QCode( 209, "JTW"),
            new QCode( 210, "JEQB"),
            new QCode( 211, "JEQW"),
            new QCode( 212, "JNEB"),
            new QCode( 213, "JNEW"),
            new QCode( 214, "IXP"),
            new QCode( 215, "LDIB"),
            new QCode( 216, "LDIW"),
            new QCode( 217, "LIAB"),
            new QCode( 218, "LIAW"),
            new QCode( 219, "STIB"),
            new QCode( 220, "STIW"),
            new QCode( 221, "IXAB"),
            new QCode( 222, "IXAW"),
            new QCode( 223, "IXA1"),
            new QCode( 224, "IXA2"),
            new QCode( 225, "IXA3"),
            new QCode( 226, "IXA4"),
            new QCode( 227, "CCALL"),
            new QCode( 228, "CENTER"),
            new QCode( 229, "CRET"),
            new QCode( 230, "EXCH"),
            new QCode( 231, "EXCH2"),
            new QCode( 232, "INCB"),
            new QCode( 233, "INCW"),
            new QCode( 234, "CALLXB"),
            new QCode( 235, "CALLXW"),
            new QCode( 236, "LDMC"),
            new QCode( 237, "LDDC"),
            new QCode( 238, "LDMW"),
            new QCode( 239, "LDDW"),
            new QCode( 240, "SETEXC"),
            new QCode( 241, "LINE"),
            new QCode( 242, "ENABLE"),
            new QCode( 243, "QRAISE"),
            new QCode( 244, "LDAP"),
            new QCode( 245, "LGLB"),
            new QCode( 246, "LGLW"),
            new QCode( 247, "ZEROMEM"),
            new QCode( 248, "EQNIL"),
            new QCode( 249, "EVENT"),
            new QCode( 250, "ROPS"),
            new QCode( 251, "INCDDS"),
            new QCode( 252, "LOPS"),
            new QCode( 253, "KOPS"),
            new QCode( 254, "BREAK"),
            new QCode( 255, "REFILLOP")
        };
    }
}

