//
// ICTCDevice.cs - Copyright (c) 2006-2024 Josh Dersch (derschjo@gmail.com)
//
// This file is part of PERQemu.
//
// PERQemu is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PERQemu is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PERQemu.  If not, see <http://www.gnu.org/licenses/>.
//

namespace PERQemu.IO.Z80
{
    /// <summary>
    /// For devices which receive a clock signal generated by the Z80 CTC or
    /// i8254 timer chip, provide a hook for notifications that the programmed
    /// rate has changed.  Used by the RS232, Speech devices.
    /// </summary>
    public interface ICTCDevice
    {
        /// <summary>
        /// Tell the device that the timer (baud rate clock) has changed.
        /// For PERQ-1 IOB/CIO, the Z80 CTC provides the baud clock (x16).
        /// For PERQ-2 EIO, the i8254 chip does it [not yet implemented].
        /// </summary>
        void NotifyRateChange(int newRate);

    }
}
